---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress1
  labels:
    app: stress1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress1
  template:
    metadata:
      labels:
        app: stress1
    spec:
      containers:
      - name: stress
        image: alanhohn/stress
        args: 
          - "--cpu"
          - "1"
          - "-v"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress2
  labels:
    app: stress2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress2
  template:
    metadata:
      labels:
        app: stress2
    spec:
      containers:
      - name: stress
        image: alanhohn/stress
        args: 
          - "--cpu"
          - "1"
          - "-v"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
